name: cryptic-variants
channels:
    - bioconda
    - conda-forge
dependencies:
  - bioconda::freyja=1.4.6
  - bioconda::minimap2=2.26
  - bioconda::nextflow=23.04.1
  - pip
  - pip:
    - python-outbreak-info==1.0.1